from .fbv import product_detail, product_list
from .cbv import ProductListAPIView, ProductDetailAPIView
from .mixins import ProductListMixinView, ProductDetailMixinView
from .generics import ProductListAPIViewGeneric, ProductDetailAPIViewGeneric, CategoryDetailAPIViewGeneric,CategoryListAPIViewGeneric